### ISSUE TITLE
Issue when i try to run the code.

### ISSUE THREAD

**Issue by GandalfsLair** [duiker101/Hacker-Typer#30]
I am getting the following error in Developer Tools when i try to run this program.

"Access to XMLHttpRequest at file:///C:/Users/user/Desktop/code.txt' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
code.txt:1 Failed to load resource: net::ERR_FAILED"

Apologies. This is likely an issue with my computer and not the code however I wonder if someone might be able to advise me on how to solve this? My lack of knowledge/experience is showing!!

The hotkeys to get the pop ups work fine, but the code.txt file is not being called...

Thanks.

**Comment by duiker101** [comment]
You need to try and run the code in a server rather than just opening the index.html file. Here are a few ways you can do it:

https://flaviocopes.com/local-web-server/

**Comment by GandalfsLair** [comment]
Many thanks... sorry for not getting back sooner - problem solved!
